### ISSUE TITLE
Lier les pages générateurs html (section jforms) / générateurs jForms (section plugins)

### ISSUE THREAD

**Issue by khena** [jelix/jelix-manuel-fr#42]
Dans la documentation des jForms (jForms > Affichage > Générateur "html"), on trouve cette phrase : 
"Voyez les plugins existants et cet interface pour comprendre la création de ce type de plugins."

Il serait plutôt intéressant faire pointer un lien vers Plugins > Générateurs jForms (quitte à rappeler dans cette page qu'on peut s'inspirer de plugins existants), afin qu'un utilisateur puisse trouver toutes les informations au même endroit (pour ma part, c'est foxmask qui m'a trouvé la page de plugins en passant par Google!)

**Comment by laurentj** [comment]
[Corrigé](https://docs.jelix.org/fr/manuel/composants/jforms/affichage/generateur-html#creer-et-ou-utiliser-un-plugin-de-widget) (je ne sais pas quand :) )
