### ISSUE TITLE
XML-RPC : Lien brisé sans raison

### ISSUE THREAD

**Issue by khena** [jelix/jelix-manuel-fr#50]
Dans la page sur le service XML-RPC, ligne 42-43
<code>Si vous utilisez [[/urls/significant|le moteur d'url significant]], vous devez
ajouter la balise suivante :</code>
le lien est brisé, mais je n'arrive pas à comprendre pourquoi. On dirait un bug du moteur du wiki (à priori, ce n'est ni lié à la virgule, ni à l'apostrophe).

**Comment by laurentj** [comment]
Ce bug n'apparait plus.
