### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by foxmask** [jelix/jelix-manuel-fr#56]
sur la page http://docs.jelix.org/fr/manuel-1.6/cache

```
Mettre en cache des données ou des portions de page HTML générées permet d'améliorer les performances du site web, voir même d'éviter de transférer des données au niveau navigateur.
```

devrait être 

```
Mettre en cache des données ou des portions de page HTML générées permet d'améliorer les performances du site web, voire même d'éviter de transférer des données au niveau navigateur.
```

La "règle" : quand on peut dire "ou bien" c'est "voire" et non voir

**Comment by foxmask** [comment]
idem ici 

    jCache est une classe permettant de stocker des données dans un système de cache. Le système repose sur des pilotes pour les accès aux données. Il est donc possible d’utiliser memcache, ou encore une base de données voir même le système de fichier.

**Comment by laurentj** [comment]
Corrigé  (manuel jelix 1.7) ;-)
