### ISSUE TITLE
La page "tests unitaires" est inaccessible

### ISSUE THREAD

**Issue by benoit-l** [jelix/jelix-manuel-fr#62]
La page tests unitaires du manuel 1.7 ne se charge pas, probablement parce que dans l'index elle est appelée "tests_unitaires" alors que son nom de fichier est "tests-unitaires" (avec un tiret)
https://github.com/jelix/jelix-manuel-fr/blob/jelix-1.7/index.gtw#L136

Au vu des autres noms de fichiers je pense que c'est l'index qu'il faudrait changer.

**Comment by laurentj** [comment]
Corrigé, merci
