### ISSUE TITLE
la doc pour jsoap est fausse + modifs qui cassent la compatibilités pas spécifiées dans la doc de migration

### ISSUE THREAD

**Issue by lejoko** [jelix/jelix-manuel-fr#66]
La doc dit d'utiliser `@param` pour spécifier les paramètres des fonctions des contrôleurs soap. Ça marchait avec Jelix 1.6, mais ça ne marche plus en 1.7 (avec les modules externes). Il faut désormais utiliser `@externalparam`. (J'ai perdu un temps fou avant de comprendre pourquoi mes contrôleurs soap ne marchaient plus correctement...). Ça devrait être spécifié aussi bien dans la doc pour soap, que comme changement incompatible dans la doc de migration. (au passage la doc du module soap est fausse aussi)

**Comment by laurentj** [comment]
Bonjour,

merci pour ce retour. C'est en effet un oubli dans la doc de jelix 1.7 (sorti en 2019), sachant que cette modification dans la lib soap a été faite en 2014..

Je vais corriger tout ça

**Comment by laurentj** [comment]
https://github.com/jelix/soap-server-module/commit/2c3c061c6084dce09bb0dce29679944cc9ab24b8

**Comment by laurentj** [comment]
La documentation est corrigée. Désolé pour cet oubli
